version: "3.8"


services:
#  web:
#    build: .
#    command: poetry run python -m src.main
#    ports:
#      - "8008:8000"
#    depends_on:
#      - db
#    env_file:
#      - ".env"
#    restart: always

  db:
    image: postgres:latest
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    env_file:
      - ".env"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    restart:
      always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
