"""add m-m to models

Revision ID: 12c6f4ab62ef
Revises: 766d756ead97
Create Date: 2023-12-01 15:35:50.005461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = "12c6f4ab62ef"
down_revision: Union[str, None] = "766d756ead97"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "book_users",
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("book_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["books.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("book_users")
    # ### end Alembic commands ###
