"""publish_year to publish_date change

Revision ID: bafbc4773660
Revises: bd89bbeccfaf
Create Date: 2023-11-29 14:40:23.021435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = "bafbc4773660"
down_revision: Union[str, None] = "bd89bbeccfaf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "books", sa.Column("publish_date", sa.DateTime(), nullable=True)
    )
    op.drop_column("books", "publish_year")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "books",
        sa.Column(
            "publish_year", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("books", "publish_date")
    # ### end Alembic commands ###
