"""add isbn number to book model

Revision ID: bd89bbeccfaf
Revises: 884548465ac4
Create Date: 2023-11-29 14:08:06.696729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = "bd89bbeccfaf"
down_revision: Union[str, None] = "884548465ac4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "books", sa.Column("isbn_number", sa.Integer(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("books", "isbn_number")
    # ### end Alembic commands ###
